config/routes.rb
RangaireApp::Application.routes.draw do
  

  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :products
  root 'static_pages#home'
  match '/about',       to: 'static_pages#about', via: 'get'
  match '/products',    to: 'static_pages#products', via: 'get'
  match '/contact',       to: 'inquiries#new', via: 'get'
  match '/contact',       to: 'inquiries#create', via: 'post'
  match '/warranty',    to: 'static_pages#warranty', via: 'get'

  resources :inquiries, :only => [:new, :create] do
    get 'thank_you', :on => :collection
  end

end

app/models/catalog.rb
class Catalog < ActiveRecord::Base
	has_attached_file :catalog
  	validates_attachment_file_name :catalog, :matches => [/pdf\Z/]
end

app/models/contact.rb
class Contact < MailForm::Base 
	attribute :name, 	:validate => true
	attribute :email,	:validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/
	attribute :message
	attribute :nickname, :captcha => true

	#Declare the email-header. it accepts anything the mail method in ActionMailer accepts

	def headers
		{
			:subject => "My Contact Form",
			:to => "colton@coltonseal.com",
			:from => %("#{name}" <#{email}>)
		}
			
	end	
end
	

app/models/inquiry.rb
# app/models/inquiry.rb

class Inquiry
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations
  include ActionView::Helpers::TextHelper
  
  attr_accessor :name, :customernumber, :nickname, :email, :customerphonenumber, :besttime, :ordernumber,
                :message, :lastname
  
  validates :name, 
            :presence => true

  validates :lastname, 
            :presence => true
  
  validates :email,
            :format => { :with => /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/ }
  
  validates :message,
            :length => { :minimum => 10, :maximum => 1000 }

  validates :nickname,
            :presence => false

  validates :customerphonenumber,
            :presence => true

  validates :besttime,
            :presence => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
  
  def deliver
    return false unless valid?
    Pony.mail({
      :from => %("#{name}" <#{email}>),
      :reply_to => email,
      :subject => "Website inquiry",
      :body => %(
        Name:                  #{name}\s#{lastname}\n
        Customer Number:       #{customernumber}\n
        Email:                 #{email}\n
        Customer Contact:      #{customerphonenumber}\n
        Best Time To Contact:  #{besttime}\n
        Order Number:          #{ordernumber}\n
        Message:               #{message})

      
      
      })
  end
      
  def persisted?
    false
  end
end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :subject, :body

  validates :name, :email, :subject, :body, :presence => true
  validates :email, :format => { :with => %r{.+@.+\..+} }, :allow_blank => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
	
	has_attached_file :spec
  	validates_attachment_file_name :spec, :matches => [/pdf\Z/]

  	self.per_page = 20

  	searchable do
    	text :spec_name, :boost => 10
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/catalogs_controller.rb
class CatalogsController < ApplicationController
	before_action :authenticate_user!, only: [:new, :edit, :destroy, :update]
  	before_action :set_product, only: [:show, :edit, :update, :destroy]


	def index
		@catalog = Catalog.all
	end

	def create
		@catalog = Catalog.new(product_params)

		if @catalog.save
      		redirect_to @catalog, notice: 'Product was successfully created.'
    	else
      		render action: 'new'
    	end
	end

	def update
		if @catalog.update(catalog_params)
	      redirect_to @catalog, notice: 'Product was successfully updated.'
	    else
	      render action: 'edit'
	    end
	end

	def new
		@catalog = Catalog.new
	end

	def destroy
	    @catalog.destroy
	    redirect_to root_url, notice: 'Product was successfully destroyed.'
	end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_catalog
      @catalog = Catalog.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def catalog_params
      params.require(:catalog).permit(:catalog)
    end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    
    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end

end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  
  def new
    @inquiry = Inquiry.new
  end
    
  def create
    @inquiry = Inquiry.new(params[:inquiry])
    if @inquiry.deliver
      render :thank_you
    else
      render :new
    end
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy, :update]
  before_action :set_product, only: [:show, :edit, :update, :destroy]


  # GET /products
  def index

    @catalog = Catalog.all
    
    @search = Product.search do
      fulltext params[:search]
     
    end
    @products = Product.where(id: @search.results.map(&:id)).page(params[:page])

  end

  # GET /products/1
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def product_params
      params.require(:product).permit(:spec_name, :spec)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def products
  end

  def contact
  end

  def warranty
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/inquiries/_form.html.erb
<%= form_for inquiry do |f| %>
  <% if inquiry.errors.any? %>
    <ul class = "errors">
      <% inquiry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

     <div style="display: none;">
      <%= f.label :nickname %><br/>
      <%= f.text_field :nickname %>
    </div>

    <div>
      <%= f.label :firstname, "First Name" %><br/>
      <%= f.text_field :name %>
    </div>
  
    <div>
      <%= f.label :lastname, "Last Name" %><br/>
      <%= f.text_field :lastname %>
    </div>

    <div>
      <%= f.label :customernumber, "Customer Number" %><br/>
      <%= f.text_field :customernumber %>
    </div>

    <div>
      <%= f.label :email, "Email" %><br/>
      <%= f.text_field :email %>
    </div>
  
    <div>
      <%= f.label :Customercontactnumber, "Customer Phone Number" %><br/>
      <%= f.text_field :customerphonenumber %>
    </div>

    <div>
      <%= f.label :Besttimetocontact, "Best Time To Contact" %><br/>
      <%= f.text_field :besttime %>
    </div>

    <div>
      <%= f.label :ordernumber, "Order Number" %><br/>
      <%= f.text_field :ordernumber %>
    </div>

    <div>
      <%= f.label :message, "Reason For Contact" %><br/>
      <%= f.text_area :message %>
    </div>
  
    <div>
      <%= f.submit "Send" %>
    </div>

  
<% end %>

app/views/inquiries/new.html.erb
<fieldset class = "container-warranty">
		<legend id = "contact-legend">CONTACT US</legend>
		<h1 class = "center down">INQUIRIES</h1>
		<p class = "center">Please fill out the form below and we'll get back to you as soon as possible.</p>

		<%= render 'form', :inquiry => @inquiry %>
	
	<div class = "contact-numbers">
		<b>PHONE:    <p style="display:inline">&nbsp(US) +1.817.556.6500</p></br>
		<b>TOLL FREE:<p style="display:inline">&nbsp(US) +1. 800.325.8351</p></b></br>
		<b>FAX:		 <p style="display:inline">&nbsp(US) +1.817.556.6549</p></b></br>
		<b>EMAIL:    <a style="display:inline" href="mailto:customerservice@rangairemfg.com">								 customerservice@rangairemfg.com</a></b>
	<div>
</fieldset>

app/views/inquiries/thank_you.html.erb
<div class = "invisible">
<h1 class = "center thankyou">THANK YOU! </h1>
<p class = "center">Your message has been recieved, we will contact you shortly</p>
</div>

app/views/layouts/_clearfooter.html.erb
<div class = "clearfooter"></div>

app/views/layouts/_footer.html.erb
<footer class = "foot">

		<div class = "foot-place">
			
			
		</div>
	
		<ul class = "phone">
			<li>PHONE 	  | &nbsp (US) +1.817.556.6511</li>
			<li>FAX 	  | &nbsp (US) +1.817.556.6549</li>
			<li>TOLL-FREE | &nbsp (US) +1.800.325.8351</li>
			<li><a href="mailto:customerservice@rangairemfg.com">customerservice@rangairemfg.com</a></li>
		</ul>
		<div class = "jensen"></div>
</footer>

app/views/layouts/_header.html.erb
<header>
		<div class="nav-bar">
			<div class = "rangaire-logo"></div>

			
		</div>
		<div class = "mfg"></div>
		<!--<div class = "space"></div>-->
		<nav>
		<ul>	
			<li>&nbsp<%= link_to("HOME", 		root_path) %> </li>
			<li>&nbsp&nbsp<%= link_to("ABOUT", 		about_path) %> </li>
			<li>&nbsp<%= link_to("PRODUCTS", 	products_path) %> </li>
			<li>&nbsp<%= link_to("CONTACT US",		contact_path) %> </li>
			<li><%= link_to("WARRANTY", 	warranty_path) %> </li>
			<% if user_signed_in? %>
			<li><%= link_to("Admin", "/admin") %></li>
			<% end %>


		</ul>
		</nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>

<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <title>Rangaire MFG | <%= yield(:title) %></title>
  <meta name="description" content="Rangaire MFG is a quality producer of Medicine Cabinets.  Since our founding, we have manufactured and distributed turn-key products for a number of trusted brands, such as Electrolux, Kenmore, Whirl- pool, GE, Broan, and NuTone.  Medicine cabinet, bath cabinet, medicine, cabinet, vanity, bathroom, fixture, Jensen, Broan, Nutone, Monarch, Triangle, American Pride, Zaca, Zenith, Basco, Masco, Kohler, Robert, Zaca, mirror, mirrored, cosmetic, tri-view, slider, cos, Rangaire, RangaireMFG, Manufacturing">
  <META NAME="ROBOTS" CONTENT="INDEX, FOLLOW">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

<!--Banner for out of date browsers-->
 <script type="text/javascript"> 
		var $buoop = {
			reminder: 0,
			test: false,
			onshow: function(infos){},
			onclick: function(infos){}

		}; 
		$buoop.ol = window.onload; 
		window.onload=function(){ 
 			try {if ($buoop.ol) $buoop.ol();}catch (e) {} 
 			var e = document.createElement("script"); 
 			e.setAttribute("type", "text/javascript"); 
 			e.setAttribute("src", "//browser-update.org/update.js"); 
 			document.body.appendChild(e); 

		} 
</script> 

	
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
<div class = "container15">
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
	<%= yield %>
</div>
	
	<%= render 'layouts/footer' %>

</body>
<div class = "space"></div>
</html>

app/views/products/_form.html.erb
<%= form_for @product, :url => products_path, :html => { :multipart => true } do |f| %>
	<%= render 'shared/error_messages', object: f.object %>
	  <%= f.label :spec_name %>
  		<%= f.text_field :spec_name %>

  <%= f.label :spec %>
  <%= f.file_field :spec %>
  
  <%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<fieldset class = "container-warranty">
	<legend class = "meowprod">PRODUCTS</legend></br></br>
		<center><%= form_tag products_path, :method => :get do %>
    
  
	      <%= text_field_tag :search, params[:search],
	       :placeholder => 'Search by Spec Sheet Name', :class => 'form-control', 
	       :style => 'width: 70%; margin-top: -3em; margin-left: -2em;' %>
	      <%= submit_tag "Search", :name => nil,
	       :class => 'btn btn-success btn-sm',
	       :style => 'width: 10%; height: 33px; margin-top: -5.5em; margin-left: 39.4em;
	       			  background-color: #1D2148; border-color: #1D2148;'%>
  		<% end %></center></br>
		<div style = "width: 900px;" class = "container">
			<!--CATALOGS-->
			<div class = "row">
				<center><h1 style = "font-size: 22px; text-decoration:underline;">
					PRODUCT CATALOGS</h1></center></br>
				<% @catalog.each do |cat| %>
				<div class = "col-md-4">
					
					 
	    	      	<div style = "padding-bottom: 1.2em;">
	    	      		<center><a style = "color: #1D2148; text-decoration:none;" 
	    	      			href="<%= cat.catalog %>" target = "_blank">
	      					<%= cat.catalog_name %>
	      				</a></center>
	      			</div>
	      				
	      			 
	      			 
				</div>
				<% end %>
			</div>
		</br></br></br>

			<!--PRODUCTS-->
			<div class = "row">
				<center><h1 style = "font-size: 22px; text-decoration:underline;">
					PRODUCT SPECIFICATIONS</h1></center></br>
				<% @products.each do |product| %>
				<div class = "col-md-4">
					
					 
	    	      	<div style = "padding-bottom: 2em;">
	    	      		<center><a style = "color: #1D2148; text-decoration:none;" 
	    	      			href="<%= product.spec %>" target = "_blank">
	      					<%= product.spec_name %>
	      				</a></center>
	      			</div>
	      				
	      			 
	      			 
				</div>
				<% end %>
			</div>
			<center><%= will_paginate @products %></center>

		</div>
	</legend>
</fieldset>



<%#= link_to 'Show', product %>
      <%#= link_to 'Edit', edit_product_path(product) %>
      <%#= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/products/new.html.erb
<h1>New product</h1>


	<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>



<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li>* <%= msg %> </li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<fieldset  class = "container-warranty">
<legend class = "meow">ABOUT US</legend>
		<p id = "warranty-para"></br>&nbsp &nbsp &nbsp Since 1948, Rangaire Manufacturing Company has been a trusted partner and source for manufactured military and consumer products. Since our founding, we have manufactured and distributed turn-key products for a number of trusted brands, such as Electrolux, Kenmore, Whirlpool, GE, Broan, and NuTone.
		<br/>
		<br/>
		&nbsp &nbsp &nbsp Headquartered in Cleburne, Texas, USA, Rangaire Manufacturing Company boasts a 215,000 square foot facility that offers customers a single source for product manufacturing and distribution. We market our own brands while also providing expertise, manufacturing, and distribution for a number of private-label products and OEM parts for a variety of industries.
		<br/>
		<br/>
		&nbsp &nbsp &nbsp Today, our keystone product is the Jensen Medicine Cabinet, a collection of medicine cabinets designed and marketed for both new construction and remodel and renovation. Whether our customers seek quality medicine cabinets at low cost, or custom-designed cabinets worthy of any luxury accommodation, our cabinets promise functionality and value for any installation.
		<br/>
		<br/>
		&nbsp &nbsp &nbsp Rangaire’s history is one of technical expertise, manufacturing excellence and relentless customer focus. While our product lines have evolved, we remain committed to providing high-quality, high- value products at competitive prices. We view our role not as a supplier, but as a partner for our customers. Our success depends on our ability to make you successful, which includes inventory management, lead time optimization, quality solutions, and cost effective products. We realize that our customers are our top priority, and we work hard to bring value to our partnerships around the world. We look forward to earning your trust and supporting your success.</p></br></br></br>

	</fieldset>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<h1>Contact Us</h1>

app/views/static_pages/home.html.erb
<% provide(:title, 'Rangaire') %>
<div class = "star"></div>
<p class = "center boxp">"Quality, Function, Value... American Made."</p>
            <div class="jcarousel-wrapper">
                <div class="jcarousel">
                    <ul>
                        <li><%= link_to image_tag("banner1.jpg", alt: :"Cabinet") %></li>
                        <li><%= link_to image_tag("banner2.jpg", alt: :"Cabinet") %></li>
                        <li><%= link_to image_tag("banner3.jpg", alt: :"Cabinet") %></li>
                        <li><%= link_to image_tag("banner4.jpg", alt: :"Cabinet") %></li>
                        <li><%= link_to image_tag("banner5.jpg", alt: :"Cabinet") %></li>
                        <li><%= link_to image_tag("banner6.jpg", alt: :"Cabinet") %></li>
                        
                        
                    </ul>
                </div>

                <a href="#" class="jcarousel-control-prev">&lsaquo;</a>
                <a href="#" class="jcarousel-control-next">&rsaquo;</a>
                
                
            </div>
        	<!--<p class="jcarousel-pagination">
                    
            </p>-->

            <div class = "space"></div>